// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/dsfs.proto

package solider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EatHandler_FileHandler_FullMethodName = "/dsfs.eatHandler/FileHandler"
)

// EatHandlerClient is the client API for EatHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EatHandlerClient interface {
	FileHandler(ctx context.Context, in *InFile, opts ...grpc.CallOption) (*Response, error)
}

type eatHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewEatHandlerClient(cc grpc.ClientConnInterface) EatHandlerClient {
	return &eatHandlerClient{cc}
}

func (c *eatHandlerClient) FileHandler(ctx context.Context, in *InFile, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, EatHandler_FileHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EatHandlerServer is the server API for EatHandler service.
// All implementations must embed UnimplementedEatHandlerServer
// for forward compatibility.
type EatHandlerServer interface {
	FileHandler(context.Context, *InFile) (*Response, error)
	mustEmbedUnimplementedEatHandlerServer()
}

// UnimplementedEatHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEatHandlerServer struct{}

func (UnimplementedEatHandlerServer) FileHandler(context.Context, *InFile) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileHandler not implemented")
}
func (UnimplementedEatHandlerServer) mustEmbedUnimplementedEatHandlerServer() {}
func (UnimplementedEatHandlerServer) testEmbeddedByValue()                    {}

// UnsafeEatHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EatHandlerServer will
// result in compilation errors.
type UnsafeEatHandlerServer interface {
	mustEmbedUnimplementedEatHandlerServer()
}

func RegisterEatHandlerServer(s grpc.ServiceRegistrar, srv EatHandlerServer) {
	// If the following call pancis, it indicates UnimplementedEatHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EatHandler_ServiceDesc, srv)
}

func _EatHandler_FileHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EatHandlerServer).FileHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EatHandler_FileHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EatHandlerServer).FileHandler(ctx, req.(*InFile))
	}
	return interceptor(ctx, in, info, handler)
}

// EatHandler_ServiceDesc is the grpc.ServiceDesc for EatHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EatHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dsfs.eatHandler",
	HandlerType: (*EatHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileHandler",
			Handler:    _EatHandler_FileHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dsfs.proto",
}
