// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: proto/dsfs.proto

package solider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datas   []byte `protobuf:"bytes,1,opt,name=datas,proto3" json:"datas,omitempty"`
	Unionid string `protobuf:"bytes,2,opt,name=unionid,proto3" json:"unionid,omitempty"`
}

func (x *InFile) Reset() {
	*x = InFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dsfs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InFile) ProtoMessage() {}

func (x *InFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dsfs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InFile.ProtoReflect.Descriptor instead.
func (*InFile) Descriptor() ([]byte, []int) {
	return file_proto_dsfs_proto_rawDescGZIP(), []int{0}
}

func (x *InFile) GetDatas() []byte {
	if x != nil {
		return x.Datas
	}
	return nil
}

func (x *InFile) GetUnionid() string {
	if x != nil {
		return x.Unionid
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code          int32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Machine       []int32 `protobuf:"varint,2,rep,packed,name=machine,proto3" json:"machine,omitempty"`
	NumberMachine []int32 `protobuf:"varint,3,rep,packed,name=numberMachine,proto3" json:"numberMachine,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dsfs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dsfs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_dsfs_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMachine() []int32 {
	if x != nil {
		return x.Machine
	}
	return nil
}

func (x *Response) GetNumberMachine() []int32 {
	if x != nil {
		return x.NumberMachine
	}
	return nil
}

var File_proto_dsfs_proto protoreflect.FileDescriptor

var file_proto_dsfs_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x73, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x64, 0x73, 0x66, 0x73, 0x22, 0x38, 0x0a, 0x06, 0x49, 0x6e, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x6f,
	0x6e, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x69, 0x64, 0x22, 0x5e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x24, 0x0a, 0x0d,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x0d, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x32, 0x39, 0x0a, 0x0a, 0x65, 0x61, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72,
	0x12, 0x2b, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12,
	0x0c, 0x2e, 0x64, 0x73, 0x66, 0x73, 0x2e, 0x49, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x1a, 0x0e, 0x2e,
	0x64, 0x73, 0x66, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x25, 0x5a,
	0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x68, 0x61,
	0x6f, 0x6e, 0x61, 0x6e, 0x30, 0x30, 0x31, 0x2f, 0x64, 0x73, 0x66, 0x73, 0x3b, 0x73, 0x6f, 0x6c,
	0x69, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dsfs_proto_rawDescOnce sync.Once
	file_proto_dsfs_proto_rawDescData = file_proto_dsfs_proto_rawDesc
)

func file_proto_dsfs_proto_rawDescGZIP() []byte {
	file_proto_dsfs_proto_rawDescOnce.Do(func() {
		file_proto_dsfs_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dsfs_proto_rawDescData)
	})
	return file_proto_dsfs_proto_rawDescData
}

var file_proto_dsfs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_dsfs_proto_goTypes = []any{
	(*InFile)(nil),   // 0: dsfs.InFile
	(*Response)(nil), // 1: dsfs.Response
}
var file_proto_dsfs_proto_depIdxs = []int32{
	0, // 0: dsfs.eatHandler.FileHandler:input_type -> dsfs.InFile
	1, // 1: dsfs.eatHandler.FileHandler:output_type -> dsfs.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dsfs_proto_init() }
func file_proto_dsfs_proto_init() {
	if File_proto_dsfs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dsfs_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*InFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dsfs_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dsfs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dsfs_proto_goTypes,
		DependencyIndexes: file_proto_dsfs_proto_depIdxs,
		MessageInfos:      file_proto_dsfs_proto_msgTypes,
	}.Build()
	File_proto_dsfs_proto = out.File
	file_proto_dsfs_proto_rawDesc = nil
	file_proto_dsfs_proto_goTypes = nil
	file_proto_dsfs_proto_depIdxs = nil
}
